app/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash

auth = Blueprint('auth', __name__, template_folder='auth_templates')

from app.forms import newUserForm, loginForm

from app.models import User, db

@auth.route('/signup', methods=['GET','POST'])
def signup():
    form = newUserForm()
    if request.method=='POST' and form.validate_on_submit():
        usernamedata = form.username.data
        emaildata = form.email.data
        passworddata = form.password.data

        new_user = User(usernamedata, passworddata, emaildata)

        db.session.add(new_user)
        db.session.commit()

        flash(f'You have successfully signed up with the username : {usernamedata}!')

        return redirect(url_for('auth.signin'))


    return render_template('signup.html', form = form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    f = loginForm()
    if request.method == 'POST' and f.validate_on_submit():
        usernamedata = f.username.data
        passworddata = f.password.data

        user = User.query.filter_by(username=usernamedata).first()
        if user is None or not check_password_hash(user.password, passworddata):
            flash(f'Incorrect username or password')
            return redirect(url_for('auth.signin'))
        
        login_user(user)
        flash(f'You have successfully signed in! Welcome {usernamedata}')
        return redirect(url_for('site.home'))


    return render_template('signin.html', form = f)

@auth.route('/signout', methods=['GET'])
def signout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
# import whatever modules/functions/classes that we need for our code to work as intended
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify

from flask_login import current_user, login_required

# import any database model we're using
from app.models import Car, db

# import our form that we're using
from app.forms import newCarForm, updateCarForm

"""
Note that in the below code, 
some arguments are specified when creating the Blueprint object. 
The first argument, "site", is the Blueprint’s name, 
which is used by Flask’s routing mechanism. 
The second argument, __name__, is the Blueprint’s import name, 
which Flask uses to locate the Blueprint’s resources.
"""
site = Blueprint('site', __name__, template_folder='site_templates')

# each webpage is defined/controlled by a flask route -> which is a python function!

# our homepage route! Hello routing :)
@site.route('/', methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
        username=current_user.username
    else:
        username = "GUEST"
    form = newCarForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            makedata = form.make.data
            modeldata = form.model.data
            yeardata = form.year.data
            pricedata = form.price.data
            descdata = form.desc.data
            imgdata = form.img.data

            print(makedata)

            # create an animal object in my database based off the form data
            new_car = Car(make=makedata, model=modeldata, year=yeardata, price=pricedata, desc=descdata, img=imgdata)

            #add the newly created animal to our database - always a two step process
            db.session.add(new_car)
            db.session.commit()

            # tell our user that we've added something - using flash messages!
            flash(f'You have successfully added the car {makedata} to your database.')

            return redirect(url_for('site.home'))
    except:
        flash(f'Invalid form input, try again.')
        return redirect(url_for('site.home'))
    return render_template('index.html', form=form, user=username)


# make second route for the profile page
@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@site.route('/cars')
def displayCars():
    a = Car.query.all()
    #car = Car.query.filter
    return render_template('display_cars.html', cars=a)

@site.route('/cars/<int:car_id>')
def individualCar(car_id):
    a = Car.query.get_or_404(car_id)
    return render_template('individual_car.html', car = a)


@site.route('/cars/update/<int:car_id>', methods=["GET", "POST"])
@login_required
def updateIndividualCar(car_id):
    a = Car.query.get_or_404(car_id)
    updateCar = updateCarForm()
    if request.method == "POST" and updateCar.validate_on_submit():
        makedata = updateCar.make.data
        modeldata = updateCar.model.data
        yeardata = updateCar.year.data
        pricedata = updateCar.price.data
        descdata = updateCar.desc.data
        imgdata = updateCar.img.data

        # deal with price being a string and needing conversion
        if updateCar.price.data:
            try:
                a.price = float(updateCar.price.data)
                print('changed price')
            except:
                flash(f"Invalid Price, couldn't update.")
                return redirect(url_for('site.individualCar', car_id=car_id))
        print('got past form data')
        #fixed update to actually update thee car if data present from the form
        if makedata:
            a.make = makedata
            print('changed make')
        if modeldata:
            a.model = modeldata
            print('changed model')
        if yeardata:
            a.year = yeardata
            print('changed year')
        if descdata:
            a.desc = descdata
            print('changed desc')
        if imgdata:
            a.img = imgdata
            print('changed img')

        print(makedata, modeldata, descdata, updateCar.price.data)

        db.session.commit

        flash(f'{a.make} has been updated!')
        return redirect(url_for('site.individualCar', car_id=car_id))

    return render_template('update_individual_car.html', car = a, form=updateCar)

@site.route('/cars/delete/<int:car_id>')
def deleteIndividualCar(car_id):
    a = Car.query.get_or_404(car_id)

    db.session.delete(a)
    db.session.commit()

    flash(f"Successfully deleted {a.make}")
    return redirect(url_for('site.displayCars'))

# Add a Public API endpoint that anyone can access to get my product information
# Note: be careful about using public API endpoints -> we can talk about authentication required api endpoints another day
# a public api endpoint can lead to unintentionally large cloud hosting costs if not set up properly
# this is a simplified and improper implementation below
@site.route('/products', methods=['GET'])
def get_products():
    """
    [GET] /products returns jsonified data on the animals within our database
    """
    # query database to get the animals
    cars = Car.query.all()
    print(cars)
    # turn the list of animal objects into a list of animal dictionaries
    cars = [car.to_dict() for car in cars]
    # jsonify that list
    cars = jsonify(cars)
    # return that list
    return cars

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="../static/css/main.css">
    <title>Drone Inventory API</title>
</head>

<body>
    {% block example %}
    {% endblock example %}


    <!--NavBar Here-->
    <nav class="ct-nav">
        <div>
            <img src="../../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
        </div>

        <!--Nav Items-->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>

                {% if current_user.is_authenticated %}

                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <!--User Auth Check for SignIn/SignUp Nav Buttons-->


                <a href="{{ url_for('auth.signout') }}">
                    <li>Sign Out</li>
                </a>


                {% else %}

                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>

                {% endif %}
                <a href="{{ url_for('site.displayCars') }}">
                    <li>List of Cars</li>
                </a>

            </ul>
        </div>
    </nav>
    <!--End of Nav-->
    <div class="container">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <!-- b4-alert-closable -->
            <div class="alert alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ message }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
    </div>


    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/form.html
<!-- HTML structure of this form as suggested by WTForms -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="make-field">
            {{ form.make.label }}
            {{ form.make(class = "form-control", placeholder = "Make...")}}
        </fieldset>
        <fieldset id="model-field">
            {{ form.model.label }}
            {{ form.model(class = "form-control", placeholder = "Model...")}}
        </fieldset>
        <fieldset id="year-field">
            {{ form.year.label }}
            {{ form.year(class = "form-control", placeholder = "Year...")}}
        </fieldset>
        <fieldset id="price-field">
            {{ form.price.label }}
            {{ form.price(class = "form-control", placeholder = "Price...")}}
        </fieldset>
        <fieldset id="desc-field">
            {{ form.desc.label }}
            {{ form.desc(class = "form-control", placeholder = "Description...")}}
        </fieldset>
        <fieldset id="img-field">
            {{ form.img.label }}
            {{ form.img(class = "form-control", placeholder = "Image URL...")}}
        </fieldset>
        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>